### ISSUE TITLE
join ebakus airdrops

### ISSUE THREAD

**Issue by abdulzabbar** [ebakus/airdrop#1]
A good project with practical ideas.Don't miss this good opportunity, there are many advantages.Which you can get, join.Very cool and promising project.More on the website: www.ebakus.com  #blockchain #ethereum #ico #cryptocurrency #ebakus #ebakusnetwork @ebakusnetwork #EBK $EBK #gamingcommunity #Gamingblockchain #ICO

**Comment by abdulzabbar** [comment]
This project has great prospects. I think it will be in demand in the market and will become a competitor to many existing platforms. 
More on the website: www.ebakus.com  #blockchain #ethereum #ico #cryptocurrency #CryptoExchange #ebakus #ebakusnetwork @ebakusnetwork #EBK $EBK #gamingcommunity #Gamingblockchain #ICO

**Comment by dzmytry** [comment]
So, this is called the blockchain Ebakus. That's what we now discuss. If to be honest, we all developed services on the basis of Ebakus focused on General utility DAPPs. That is, developers Ebakus purposefully created a concept under the protection of, compliance with and further the enjoyment of each individual DAPPs applications. For this, the founders Ebakus reviewed a number of existing limitations in already available on the market blockchain proposals and came to the conclusion that if each of them were not good at it still have a brake that allows 100% satisfy DAPPs applications. This can be easily attributed to all sorts of commissions arising from various transactions, and other power limitations which blocks the mass flow of participants in a particular direction.
